# Generated by Django 6.0.3 on 2026-04-02 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('percent_off', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('cta_text', models.CharField(default='Learn More', max_length=60)),
                ('cta_url', models.URLField()),
                ('offer_type', models.CharField(choices=[('playbook', 'Playbook'), ('app', 'App'), ('community', 'Community'), ('event', 'Next Event'), ('consulting', 'Consulting')], default='app', max_length=20)),
                ('is_vip_only', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('photo_url', models.URLField(blank=True)),
                ('talk_title', models.CharField(max_length=200)),
                ('key_insights', models.TextField(help_text='One insight per line.')),
                ('extra_details', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo_url', models.URLField()),
                ('website', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='One feature per line.')),
                ('is_highlighted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('attended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discountcode')),
                ('ticket_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tickettier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('session_type', models.CharField(choices=[('welcome', 'Welcome'), ('speaker', 'Speaker Session'), ('qa', 'Q&A'), ('closing', 'Closing')], default='speaker', max_length=20)),
                ('color_hex', models.CharField(default='#1e5b4f', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.speaker')),
            ],
            options={
                'ordering': ['start_time', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='discountcode',
            name='ticket_tier',
            field=models.ForeignKey(blank=True, help_text='Leave blank to allow all tiers.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tickettier'),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('confirmation', 'Confirmation'), ('post_webinar_playbook', 'Post Webinar Playbook'), ('post_webinar_offer', 'Post Webinar Offer')], max_length=40)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registration')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('registration', 'email_type')},
            },
        ),
    ]
